[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "16"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200