[build]
  base = "frontend/"
  publish = "dist/"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200