name: Deploy Frontend to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow whenever pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload frontend folder
      uses: actions/upload-pages-artifact@v2
      with:
        path: frontend

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
